INSERT INTO attack(id, name, type) VALUES (1, "Pound", "normal");
INSERT INTO attack(id, name, type) VALUES (2, "Karate Chop", "fighting");
INSERT INTO attack(id, name, type) VALUES (3, "Double Slap", "normal");
INSERT INTO attack(id, name, type) VALUES (4, "Comet Punch", "normal");
INSERT INTO attack(id, name, type) VALUES (5, "Mega Punch", "normal");
INSERT INTO attack(id, name, type) VALUES (6, "Pay Day", "normal");
INSERT INTO attack(id, name, type) VALUES (7, "Fire Punch", "fire");
INSERT INTO attack(id, name, type) VALUES (8, "Ice Punch", "ice");
INSERT INTO attack(id, name, type) VALUES (9, "Thunder Punch", "electric");
INSERT INTO attack(id, name, type) VALUES (10, "Scratch", "normal");
INSERT INTO attack(id, name, type) VALUES (11, "Vise Grip", "normal");
INSERT INTO attack(id, name, type) VALUES (12, "Guillotine", "normal");
INSERT INTO attack(id, name, type) VALUES (13, "Razor Wind", "normal");
INSERT INTO attack(id, name, type) VALUES (14, "Swords Dance", "normal");
INSERT INTO attack(id, name, type) VALUES (15, "Cut", "normal");
INSERT INTO attack(id, name, type) VALUES (16, "Gust", "flying");
INSERT INTO attack(id, name, type) VALUES (17, "Wing Attack", "flying");
INSERT INTO attack(id, name, type) VALUES (18, "Whirlwind", "normal");
INSERT INTO attack(id, name, type) VALUES (19, "Fly", "flying");
INSERT INTO attack(id, name, type) VALUES (20, "Bind", "normal");
INSERT INTO attack(id, name, type) VALUES (21, "Slam", "normal");
INSERT INTO attack(id, name, type) VALUES (22, "Vine Whip", "grass");
INSERT INTO attack(id, name, type) VALUES (23, "Stomp", "normal");
INSERT INTO attack(id, name, type) VALUES (24, "Double Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (25, "Mega Kick", "normal");
INSERT INTO attack(id, name, type) VALUES (26, "Jump Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (27, "Rolling Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (28, "Sand Attack", "ground");
INSERT INTO attack(id, name, type) VALUES (29, "Headbutt", "normal");
INSERT INTO attack(id, name, type) VALUES (30, "Horn Attack", "normal");
INSERT INTO attack(id, name, type) VALUES (31, "Fury Attack", "normal");
INSERT INTO attack(id, name, type) VALUES (32, "Horn Drill", "normal");
INSERT INTO attack(id, name, type) VALUES (33, "Tackle", "normal");
INSERT INTO attack(id, name, type) VALUES (34, "Body Slam", "normal");
INSERT INTO attack(id, name, type) VALUES (35, "Wrap", "normal");
INSERT INTO attack(id, name, type) VALUES (36, "Take Down", "normal");
INSERT INTO attack(id, name, type) VALUES (37, "Thrash", "normal");
INSERT INTO attack(id, name, type) VALUES (38, "Double-Edge", "normal");
INSERT INTO attack(id, name, type) VALUES (39, "Tail Whip", "normal");
INSERT INTO attack(id, name, type) VALUES (40, "Poison Sting", "poison");
INSERT INTO attack(id, name, type) VALUES (41, "Twineedle", "bug");
INSERT INTO attack(id, name, type) VALUES (42, "Pin Missile", "bug");
INSERT INTO attack(id, name, type) VALUES (43, "Leer", "normal");
INSERT INTO attack(id, name, type) VALUES (44, "Bite", "dark");
INSERT INTO attack(id, name, type) VALUES (45, "Growl", "normal");
INSERT INTO attack(id, name, type) VALUES (46, "Roar", "normal");
INSERT INTO attack(id, name, type) VALUES (47, "Sing", "normal");
INSERT INTO attack(id, name, type) VALUES (48, "Supersonic", "normal");
INSERT INTO attack(id, name, type) VALUES (49, "Sonic Boom", "normal");
INSERT INTO attack(id, name, type) VALUES (50, "Disable", "normal");
INSERT INTO attack(id, name, type) VALUES (51, "Acid", "poison");
INSERT INTO attack(id, name, type) VALUES (52, "Ember", "fire");
INSERT INTO attack(id, name, type) VALUES (53, "Flamethrower", "fire");
INSERT INTO attack(id, name, type) VALUES (54, "Mist", "ice");
INSERT INTO attack(id, name, type) VALUES (55, "Water Gun", "water");
INSERT INTO attack(id, name, type) VALUES (56, "Hydro Pump", "water");
INSERT INTO attack(id, name, type) VALUES (57, "Surf", "water");
INSERT INTO attack(id, name, type) VALUES (58, "Ice Beam", "ice");
INSERT INTO attack(id, name, type) VALUES (59, "Blizzard", "ice");
INSERT INTO attack(id, name, type) VALUES (60, "Psybeam", "psychic");
INSERT INTO attack(id, name, type) VALUES (61, "Bubble Beam", "water");
INSERT INTO attack(id, name, type) VALUES (62, "Aurora Beam", "ice");
INSERT INTO attack(id, name, type) VALUES (63, "Hyper Beam", "normal");
INSERT INTO attack(id, name, type) VALUES (64, "Peck", "flying");
INSERT INTO attack(id, name, type) VALUES (65, "Drill Peck", "flying");
INSERT INTO attack(id, name, type) VALUES (66, "Submission", "fighting");
INSERT INTO attack(id, name, type) VALUES (67, "Low Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (68, "Counter", "fighting");
INSERT INTO attack(id, name, type) VALUES (69, "Seismic Toss", "fighting");
INSERT INTO attack(id, name, type) VALUES (70, "Strength", "normal");
INSERT INTO attack(id, name, type) VALUES (71, "Absorb", "grass");
INSERT INTO attack(id, name, type) VALUES (72, "Mega Drain", "grass");
INSERT INTO attack(id, name, type) VALUES (73, "Leech Seed", "grass");
INSERT INTO attack(id, name, type) VALUES (74, "Growth", "normal");
INSERT INTO attack(id, name, type) VALUES (75, "Razor Leaf", "grass");
INSERT INTO attack(id, name, type) VALUES (76, "Solar Beam", "grass");
INSERT INTO attack(id, name, type) VALUES (77, "Poison Powder", "poison");
INSERT INTO attack(id, name, type) VALUES (78, "Stun Spore", "grass");
INSERT INTO attack(id, name, type) VALUES (79, "Sleep Powder", "grass");
INSERT INTO attack(id, name, type) VALUES (80, "Petal Dance", "grass");
INSERT INTO attack(id, name, type) VALUES (81, "String Shot", "bug");
INSERT INTO attack(id, name, type) VALUES (82, "Dragon Rage", "dragon");
INSERT INTO attack(id, name, type) VALUES (83, "Fire Spin", "fire");
INSERT INTO attack(id, name, type) VALUES (84, "Thunder Shock", "electric");
INSERT INTO attack(id, name, type) VALUES (85, "Thunderbolt", "electric");
INSERT INTO attack(id, name, type) VALUES (86, "Thunder Wave", "electric");
INSERT INTO attack(id, name, type) VALUES (87, "Thunder", "electric");
INSERT INTO attack(id, name, type) VALUES (88, "Rock Throw", "rock");
INSERT INTO attack(id, name, type) VALUES (89, "Earthquake", "ground");
INSERT INTO attack(id, name, type) VALUES (90, "Fissure", "ground");
INSERT INTO attack(id, name, type) VALUES (91, "Dig", "ground");
INSERT INTO attack(id, name, type) VALUES (92, "Toxic", "poison");
INSERT INTO attack(id, name, type) VALUES (93, "Confusion", "psychic");
INSERT INTO attack(id, name, type) VALUES (94, "Psychic", "psychic");
INSERT INTO attack(id, name, type) VALUES (95, "Hypnosis", "psychic");
INSERT INTO attack(id, name, type) VALUES (96, "Meditate", "psychic");
INSERT INTO attack(id, name, type) VALUES (97, "Agility", "psychic");
INSERT INTO attack(id, name, type) VALUES (98, "Quick Attack", "normal");
INSERT INTO attack(id, name, type) VALUES (99, "Rage", "normal");
INSERT INTO attack(id, name, type) VALUES (100, "Teleport", "psychic");
INSERT INTO attack(id, name, type) VALUES (101, "Night Shade", "ghost");
INSERT INTO attack(id, name, type) VALUES (102, "Mimic", "normal");
INSERT INTO attack(id, name, type) VALUES (103, "Screech", "normal");
INSERT INTO attack(id, name, type) VALUES (104, "Double Team", "normal");
INSERT INTO attack(id, name, type) VALUES (105, "Recover", "normal");
INSERT INTO attack(id, name, type) VALUES (106, "Harden", "normal");
INSERT INTO attack(id, name, type) VALUES (107, "Minimize", "normal");
INSERT INTO attack(id, name, type) VALUES (108, "Smokescreen", "normal");
INSERT INTO attack(id, name, type) VALUES (109, "Confuse Ray", "ghost");
INSERT INTO attack(id, name, type) VALUES (110, "Withdraw", "water");
INSERT INTO attack(id, name, type) VALUES (111, "Defense Curl", "normal");
INSERT INTO attack(id, name, type) VALUES (112, "Barrier", "psychic");
INSERT INTO attack(id, name, type) VALUES (113, "Light Screen", "psychic");
INSERT INTO attack(id, name, type) VALUES (114, "Haze", "ice");
INSERT INTO attack(id, name, type) VALUES (115, "Reflect", "psychic");
INSERT INTO attack(id, name, type) VALUES (116, "Focus Energy", "normal");
INSERT INTO attack(id, name, type) VALUES (117, "Bide", "normal");
INSERT INTO attack(id, name, type) VALUES (118, "Metronome", "normal");
INSERT INTO attack(id, name, type) VALUES (119, "Mirror Move", "flying");
INSERT INTO attack(id, name, type) VALUES (120, "Self-Destruct", "normal");
INSERT INTO attack(id, name, type) VALUES (121, "Egg Bomb", "normal");
INSERT INTO attack(id, name, type) VALUES (122, "Lick", "ghost");
INSERT INTO attack(id, name, type) VALUES (123, "Smog", "poison");
INSERT INTO attack(id, name, type) VALUES (124, "Sludge", "poison");
INSERT INTO attack(id, name, type) VALUES (125, "Bone Club", "ground");
INSERT INTO attack(id, name, type) VALUES (126, "Fire Blast", "fire");
INSERT INTO attack(id, name, type) VALUES (127, "Waterfall", "water");
INSERT INTO attack(id, name, type) VALUES (128, "Clamp", "water");
INSERT INTO attack(id, name, type) VALUES (129, "Swift", "normal");
INSERT INTO attack(id, name, type) VALUES (130, "Skull Bash", "normal");
INSERT INTO attack(id, name, type) VALUES (131, "Spike Cannon", "normal");
INSERT INTO attack(id, name, type) VALUES (132, "Constrict", "normal");
INSERT INTO attack(id, name, type) VALUES (133, "Amnesia", "psychic");
INSERT INTO attack(id, name, type) VALUES (134, "Kinesis", "psychic");
INSERT INTO attack(id, name, type) VALUES (135, "Soft-Boiled", "normal");
INSERT INTO attack(id, name, type) VALUES (136, "High Jump Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (137, "Glare", "normal");
INSERT INTO attack(id, name, type) VALUES (138, "Dream Eater", "psychic");
INSERT INTO attack(id, name, type) VALUES (139, "Poison Gas", "poison");
INSERT INTO attack(id, name, type) VALUES (140, "Barrage", "normal");
INSERT INTO attack(id, name, type) VALUES (141, "Leech Life", "bug");
INSERT INTO attack(id, name, type) VALUES (142, "Lovely Kiss", "normal");
INSERT INTO attack(id, name, type) VALUES (143, "Sky Attack", "flying");
INSERT INTO attack(id, name, type) VALUES (144, "Transform", "normal");
INSERT INTO attack(id, name, type) VALUES (145, "Bubble", "water");
INSERT INTO attack(id, name, type) VALUES (146, "Dizzy Punch", "normal");
INSERT INTO attack(id, name, type) VALUES (147, "Spore", "grass");
INSERT INTO attack(id, name, type) VALUES (148, "Flash", "normal");
INSERT INTO attack(id, name, type) VALUES (149, "Psywave", "psychic");
INSERT INTO attack(id, name, type) VALUES (150, "Splash", "normal");
INSERT INTO attack(id, name, type) VALUES (151, "Acid Armor", "poison");
INSERT INTO attack(id, name, type) VALUES (152, "Crabhammer", "water");
INSERT INTO attack(id, name, type) VALUES (153, "Explosion", "normal");
INSERT INTO attack(id, name, type) VALUES (154, "Fury Swipes", "normal");
INSERT INTO attack(id, name, type) VALUES (155, "Bonemerang", "ground");
INSERT INTO attack(id, name, type) VALUES (156, "Rest", "psychic");
INSERT INTO attack(id, name, type) VALUES (157, "Rock Slide", "rock");
INSERT INTO attack(id, name, type) VALUES (158, "Hyper Fang", "normal");
INSERT INTO attack(id, name, type) VALUES (159, "Sharpen", "normal");
INSERT INTO attack(id, name, type) VALUES (160, "Conversion", "normal");
INSERT INTO attack(id, name, type) VALUES (161, "Tri Attack", "normal");
INSERT INTO attack(id, name, type) VALUES (162, "Super Fang", "normal");
INSERT INTO attack(id, name, type) VALUES (163, "Slash", "normal");
INSERT INTO attack(id, name, type) VALUES (164, "Substitute", "normal");
INSERT INTO attack(id, name, type) VALUES (165, "Struggle", "normal");
INSERT INTO attack(id, name, type) VALUES (166, "Sketch", "normal");
INSERT INTO attack(id, name, type) VALUES (167, "Triple Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (168, "Thief", "dark");
INSERT INTO attack(id, name, type) VALUES (169, "Spider Web", "bug");
INSERT INTO attack(id, name, type) VALUES (170, "Mind Reader", "normal");
INSERT INTO attack(id, name, type) VALUES (171, "Nightmare", "ghost");
INSERT INTO attack(id, name, type) VALUES (172, "Flame Wheel", "fire");
INSERT INTO attack(id, name, type) VALUES (173, "Snore", "normal");
INSERT INTO attack(id, name, type) VALUES (174, "Curse", "ghost");
INSERT INTO attack(id, name, type) VALUES (175, "Flail", "normal");
INSERT INTO attack(id, name, type) VALUES (176, "Conversion 2", "normal");
INSERT INTO attack(id, name, type) VALUES (177, "Aeroblast", "flying");
INSERT INTO attack(id, name, type) VALUES (178, "Cotton Spore", "grass");
INSERT INTO attack(id, name, type) VALUES (179, "Reversal", "fighting");
INSERT INTO attack(id, name, type) VALUES (180, "Spite", "ghost");
INSERT INTO attack(id, name, type) VALUES (181, "Powder Snow", "ice");
INSERT INTO attack(id, name, type) VALUES (182, "Protect", "normal");
INSERT INTO attack(id, name, type) VALUES (183, "Mach Punch", "fighting");
INSERT INTO attack(id, name, type) VALUES (184, "Scary Face", "normal");
INSERT INTO attack(id, name, type) VALUES (185, "Feint Attack", "dark");
INSERT INTO attack(id, name, type) VALUES (186, "Sweet Kiss", "fairy");
INSERT INTO attack(id, name, type) VALUES (187, "Belly Drum", "normal");
INSERT INTO attack(id, name, type) VALUES (188, "Sludge Bomb", "poison");
INSERT INTO attack(id, name, type) VALUES (189, "Mud-Slap", "ground");
INSERT INTO attack(id, name, type) VALUES (190, "Octazooka", "water");
INSERT INTO attack(id, name, type) VALUES (191, "Spikes", "ground");
INSERT INTO attack(id, name, type) VALUES (192, "Zap Cannon", "electric");
INSERT INTO attack(id, name, type) VALUES (193, "Foresight", "normal");
INSERT INTO attack(id, name, type) VALUES (194, "Destiny Bond", "ghost");
INSERT INTO attack(id, name, type) VALUES (195, "Perish Song", "normal");
INSERT INTO attack(id, name, type) VALUES (196, "Icy Wind", "ice");
INSERT INTO attack(id, name, type) VALUES (197, "Detect", "fighting");
INSERT INTO attack(id, name, type) VALUES (198, "Bone Rush", "ground");
INSERT INTO attack(id, name, type) VALUES (199, "Lock-On", "normal");
INSERT INTO attack(id, name, type) VALUES (200, "Outrage", "dragon");
INSERT INTO attack(id, name, type) VALUES (201, "Sandstorm", "rock");
INSERT INTO attack(id, name, type) VALUES (202, "Giga Drain", "grass");
INSERT INTO attack(id, name, type) VALUES (203, "Endure", "normal");
INSERT INTO attack(id, name, type) VALUES (204, "Charm", "fairy");
INSERT INTO attack(id, name, type) VALUES (205, "Rollout", "rock");
INSERT INTO attack(id, name, type) VALUES (206, "False Swipe", "normal");
INSERT INTO attack(id, name, type) VALUES (207, "Swagger", "normal");
INSERT INTO attack(id, name, type) VALUES (208, "Milk Drink", "normal");
INSERT INTO attack(id, name, type) VALUES (209, "Spark", "electric");
INSERT INTO attack(id, name, type) VALUES (210, "Fury Cutter", "bug");
INSERT INTO attack(id, name, type) VALUES (211, "Steel Wing", "steel");
INSERT INTO attack(id, name, type) VALUES (212, "Mean Look", "normal");
INSERT INTO attack(id, name, type) VALUES (213, "Attract", "normal");
INSERT INTO attack(id, name, type) VALUES (214, "Sleep Talk", "normal");
INSERT INTO attack(id, name, type) VALUES (215, "Heal Bell", "normal");
INSERT INTO attack(id, name, type) VALUES (216, "Return", "normal");
INSERT INTO attack(id, name, type) VALUES (217, "Present", "normal");
INSERT INTO attack(id, name, type) VALUES (218, "Frustration", "normal");
INSERT INTO attack(id, name, type) VALUES (219, "Safeguard", "normal");
INSERT INTO attack(id, name, type) VALUES (220, "Pain Split", "normal");
INSERT INTO attack(id, name, type) VALUES (221, "Sacred Fire", "fire");
INSERT INTO attack(id, name, type) VALUES (222, "Magnitude", "ground");
INSERT INTO attack(id, name, type) VALUES (223, "Dynamic Punch", "fighting");
INSERT INTO attack(id, name, type) VALUES (224, "Megahorn", "bug");
INSERT INTO attack(id, name, type) VALUES (225, "Dragon Breath", "dragon");
INSERT INTO attack(id, name, type) VALUES (226, "Baton Pass", "normal");
INSERT INTO attack(id, name, type) VALUES (227, "Encore", "normal");
INSERT INTO attack(id, name, type) VALUES (228, "Pursuit", "dark");
INSERT INTO attack(id, name, type) VALUES (229, "Rapid Spin", "normal");
INSERT INTO attack(id, name, type) VALUES (230, "Sweet Scent", "normal");
INSERT INTO attack(id, name, type) VALUES (231, "Iron Tail", "steel");
INSERT INTO attack(id, name, type) VALUES (232, "Metal Claw", "steel");
INSERT INTO attack(id, name, type) VALUES (233, "Vital Throw", "fighting");
INSERT INTO attack(id, name, type) VALUES (234, "Morning Sun", "normal");
INSERT INTO attack(id, name, type) VALUES (235, "Synthesis", "grass");
INSERT INTO attack(id, name, type) VALUES (236, "Moonlight", "fairy");
INSERT INTO attack(id, name, type) VALUES (237, "Hidden Power", "normal");
INSERT INTO attack(id, name, type) VALUES (238, "Cross Chop", "fighting");
INSERT INTO attack(id, name, type) VALUES (239, "Twister", "dragon");
INSERT INTO attack(id, name, type) VALUES (240, "Rain Dance", "water");
INSERT INTO attack(id, name, type) VALUES (241, "Sunny Day", "fire");
INSERT INTO attack(id, name, type) VALUES (242, "Crunch", "dark");
INSERT INTO attack(id, name, type) VALUES (243, "Mirror Coat", "psychic");
INSERT INTO attack(id, name, type) VALUES (244, "Psych Up", "normal");
INSERT INTO attack(id, name, type) VALUES (245, "Extreme Speed", "normal");
INSERT INTO attack(id, name, type) VALUES (246, "Ancient Power", "rock");
INSERT INTO attack(id, name, type) VALUES (247, "Shadow Ball", "ghost");
INSERT INTO attack(id, name, type) VALUES (248, "Future Sight", "psychic");
INSERT INTO attack(id, name, type) VALUES (249, "Rock Smash", "fighting");
INSERT INTO attack(id, name, type) VALUES (250, "Whirlpool", "water");
INSERT INTO attack(id, name, type) VALUES (251, "Beat Up", "dark");
INSERT INTO attack(id, name, type) VALUES (252, "Fake Out", "normal");
INSERT INTO attack(id, name, type) VALUES (253, "Uproar", "normal");
INSERT INTO attack(id, name, type) VALUES (254, "Stockpile", "normal");
INSERT INTO attack(id, name, type) VALUES (255, "Spit Up", "normal");
INSERT INTO attack(id, name, type) VALUES (256, "Swallow", "normal");
INSERT INTO attack(id, name, type) VALUES (257, "Heat Wave", "fire");
INSERT INTO attack(id, name, type) VALUES (258, "Hail", "ice");
INSERT INTO attack(id, name, type) VALUES (259, "Torment", "dark");
INSERT INTO attack(id, name, type) VALUES (260, "Flatter", "dark");
INSERT INTO attack(id, name, type) VALUES (261, "Will-O-Wisp", "fire");
INSERT INTO attack(id, name, type) VALUES (262, "Memento", "dark");
INSERT INTO attack(id, name, type) VALUES (263, "Facade", "normal");
INSERT INTO attack(id, name, type) VALUES (264, "Focus Punch", "fighting");
INSERT INTO attack(id, name, type) VALUES (265, "Smelling Salts", "normal");
INSERT INTO attack(id, name, type) VALUES (266, "Follow Me", "normal");
INSERT INTO attack(id, name, type) VALUES (267, "Nature Power", "normal");
INSERT INTO attack(id, name, type) VALUES (268, "Charge", "electric");
INSERT INTO attack(id, name, type) VALUES (269, "Taunt", "dark");
INSERT INTO attack(id, name, type) VALUES (270, "Helping Hand", "normal");
INSERT INTO attack(id, name, type) VALUES (271, "Trick", "psychic");
INSERT INTO attack(id, name, type) VALUES (272, "Role Play", "psychic");
INSERT INTO attack(id, name, type) VALUES (273, "Wish", "normal");
INSERT INTO attack(id, name, type) VALUES (274, "Assist", "normal");
INSERT INTO attack(id, name, type) VALUES (275, "Ingrain", "grass");
INSERT INTO attack(id, name, type) VALUES (276, "Superpower", "fighting");
INSERT INTO attack(id, name, type) VALUES (277, "Magic Coat", "psychic");
INSERT INTO attack(id, name, type) VALUES (278, "Recycle", "normal");
INSERT INTO attack(id, name, type) VALUES (279, "Revenge", "fighting");
INSERT INTO attack(id, name, type) VALUES (280, "Brick Break", "fighting");
INSERT INTO attack(id, name, type) VALUES (281, "Yawn", "normal");
INSERT INTO attack(id, name, type) VALUES (282, "Knock Off", "dark");
INSERT INTO attack(id, name, type) VALUES (283, "Endeavor", "normal");
INSERT INTO attack(id, name, type) VALUES (284, "Eruption", "fire");
INSERT INTO attack(id, name, type) VALUES (285, "Skill Swap", "psychic");
INSERT INTO attack(id, name, type) VALUES (286, "Imprison", "psychic");
INSERT INTO attack(id, name, type) VALUES (287, "Refresh", "normal");
INSERT INTO attack(id, name, type) VALUES (288, "Grudge", "ghost");
INSERT INTO attack(id, name, type) VALUES (289, "Snatch", "dark");
INSERT INTO attack(id, name, type) VALUES (290, "Secret Power", "normal");
INSERT INTO attack(id, name, type) VALUES (291, "Dive", "water");
INSERT INTO attack(id, name, type) VALUES (292, "Arm Thrust", "fighting");
INSERT INTO attack(id, name, type) VALUES (293, "Camouflage", "normal");
INSERT INTO attack(id, name, type) VALUES (294, "Tail Glow", "bug");
INSERT INTO attack(id, name, type) VALUES (295, "Luster Purge", "psychic");
INSERT INTO attack(id, name, type) VALUES (296, "Mist Ball", "psychic");
INSERT INTO attack(id, name, type) VALUES (297, "Feather Dance", "flying");
INSERT INTO attack(id, name, type) VALUES (298, "Teeter Dance", "normal");
INSERT INTO attack(id, name, type) VALUES (299, "Blaze Kick", "fire");
INSERT INTO attack(id, name, type) VALUES (300, "Mud Sport", "ground");
INSERT INTO attack(id, name, type) VALUES (301, "Ice Ball", "ice");
INSERT INTO attack(id, name, type) VALUES (302, "Needle Arm", "grass");
INSERT INTO attack(id, name, type) VALUES (303, "Slack Off", "normal");
INSERT INTO attack(id, name, type) VALUES (304, "Hyper Voice", "normal");
INSERT INTO attack(id, name, type) VALUES (305, "Poison Fang", "poison");
INSERT INTO attack(id, name, type) VALUES (306, "Crush Claw", "normal");
INSERT INTO attack(id, name, type) VALUES (307, "Blast Burn", "fire");
INSERT INTO attack(id, name, type) VALUES (308, "Hydro Cannon", "water");
INSERT INTO attack(id, name, type) VALUES (309, "Meteor Mash", "steel");
INSERT INTO attack(id, name, type) VALUES (310, "Astonish", "ghost");
INSERT INTO attack(id, name, type) VALUES (311, "Weather Ball", "normal");
INSERT INTO attack(id, name, type) VALUES (312, "Aromatherapy", "grass");
INSERT INTO attack(id, name, type) VALUES (313, "Fake Tears", "dark");
INSERT INTO attack(id, name, type) VALUES (314, "Air Cutter", "flying");
INSERT INTO attack(id, name, type) VALUES (315, "Overheat", "fire");
INSERT INTO attack(id, name, type) VALUES (316, "Odor Sleuth", "normal");
INSERT INTO attack(id, name, type) VALUES (317, "Rock Tomb", "rock");
INSERT INTO attack(id, name, type) VALUES (318, "Silver Wind", "bug");
INSERT INTO attack(id, name, type) VALUES (319, "Metal Sound", "steel");
INSERT INTO attack(id, name, type) VALUES (320, "Grass Whistle", "grass");
INSERT INTO attack(id, name, type) VALUES (321, "Tickle", "normal");
INSERT INTO attack(id, name, type) VALUES (322, "Cosmic Power", "psychic");
INSERT INTO attack(id, name, type) VALUES (323, "Water Spout", "water");
INSERT INTO attack(id, name, type) VALUES (324, "Signal Beam", "bug");
INSERT INTO attack(id, name, type) VALUES (325, "Shadow Punch", "ghost");
INSERT INTO attack(id, name, type) VALUES (326, "Extrasensory", "psychic");
INSERT INTO attack(id, name, type) VALUES (327, "Sky Uppercut", "fighting");
INSERT INTO attack(id, name, type) VALUES (328, "Sand Tomb", "ground");
INSERT INTO attack(id, name, type) VALUES (329, "Sheer Cold", "ice");
INSERT INTO attack(id, name, type) VALUES (330, "Muddy Water", "water");
INSERT INTO attack(id, name, type) VALUES (331, "Bullet Seed", "grass");
INSERT INTO attack(id, name, type) VALUES (332, "Aerial Ace", "flying");
INSERT INTO attack(id, name, type) VALUES (333, "Icicle Spear", "ice");
INSERT INTO attack(id, name, type) VALUES (334, "Iron Defense", "steel");
INSERT INTO attack(id, name, type) VALUES (335, "Block", "normal");
INSERT INTO attack(id, name, type) VALUES (336, "Howl", "normal");
INSERT INTO attack(id, name, type) VALUES (337, "Dragon Claw", "dragon");
INSERT INTO attack(id, name, type) VALUES (338, "Frenzy Plant", "grass");
INSERT INTO attack(id, name, type) VALUES (339, "Bulk Up", "fighting");
INSERT INTO attack(id, name, type) VALUES (340, "Bounce", "flying");
INSERT INTO attack(id, name, type) VALUES (341, "Mud Shot", "ground");
INSERT INTO attack(id, name, type) VALUES (342, "Poison Tail", "poison");
INSERT INTO attack(id, name, type) VALUES (343, "Covet", "normal");
INSERT INTO attack(id, name, type) VALUES (344, "Volt Tackle", "electric");
INSERT INTO attack(id, name, type) VALUES (345, "Magical Leaf", "grass");
INSERT INTO attack(id, name, type) VALUES (346, "Water Sport", "water");
INSERT INTO attack(id, name, type) VALUES (347, "Calm Mind", "psychic");
INSERT INTO attack(id, name, type) VALUES (348, "Leaf Blade", "grass");
INSERT INTO attack(id, name, type) VALUES (349, "Dragon Dance", "dragon");
INSERT INTO attack(id, name, type) VALUES (350, "Rock Blast", "rock");
INSERT INTO attack(id, name, type) VALUES (351, "Shock Wave", "electric");
INSERT INTO attack(id, name, type) VALUES (352, "Water Pulse", "water");
INSERT INTO attack(id, name, type) VALUES (353, "Doom Desire", "steel");
INSERT INTO attack(id, name, type) VALUES (354, "Psycho Boost", "psychic");
INSERT INTO attack(id, name, type) VALUES (355, "Roost", "flying");
INSERT INTO attack(id, name, type) VALUES (356, "Gravity", "psychic");
INSERT INTO attack(id, name, type) VALUES (357, "Miracle Eye", "psychic");
INSERT INTO attack(id, name, type) VALUES (358, "Wake-Up Slap", "fighting");
INSERT INTO attack(id, name, type) VALUES (359, "Hammer Arm", "fighting");
INSERT INTO attack(id, name, type) VALUES (360, "Gyro Ball", "steel");
INSERT INTO attack(id, name, type) VALUES (361, "Healing Wish", "psychic");
INSERT INTO attack(id, name, type) VALUES (362, "Brine", "water");
INSERT INTO attack(id, name, type) VALUES (363, "Natural Gift", "normal");
INSERT INTO attack(id, name, type) VALUES (364, "Feint", "normal");
INSERT INTO attack(id, name, type) VALUES (365, "Pluck", "flying");
INSERT INTO attack(id, name, type) VALUES (366, "Tailwind", "flying");
INSERT INTO attack(id, name, type) VALUES (367, "Acupressure", "normal");
INSERT INTO attack(id, name, type) VALUES (368, "Metal Burst", "steel");
INSERT INTO attack(id, name, type) VALUES (369, "U-turn", "bug");
INSERT INTO attack(id, name, type) VALUES (370, "Close Combat", "fighting");
INSERT INTO attack(id, name, type) VALUES (371, "Payback", "dark");
INSERT INTO attack(id, name, type) VALUES (372, "Assurance", "dark");
INSERT INTO attack(id, name, type) VALUES (373, "Embargo", "dark");
INSERT INTO attack(id, name, type) VALUES (374, "Fling", "dark");
INSERT INTO attack(id, name, type) VALUES (375, "Psycho Shift", "psychic");
INSERT INTO attack(id, name, type) VALUES (376, "Trump Card", "normal");
INSERT INTO attack(id, name, type) VALUES (377, "Heal Block", "psychic");
INSERT INTO attack(id, name, type) VALUES (378, "Wring Out", "normal");
INSERT INTO attack(id, name, type) VALUES (379, "Power Trick", "psychic");
INSERT INTO attack(id, name, type) VALUES (380, "Gastro Acid", "poison");
INSERT INTO attack(id, name, type) VALUES (381, "Lucky Chant", "normal");
INSERT INTO attack(id, name, type) VALUES (382, "Me First", "normal");
INSERT INTO attack(id, name, type) VALUES (383, "Copycat", "normal");
INSERT INTO attack(id, name, type) VALUES (384, "Power Swap", "psychic");
INSERT INTO attack(id, name, type) VALUES (385, "Guard Swap", "psychic");
INSERT INTO attack(id, name, type) VALUES (386, "Punishment", "dark");
INSERT INTO attack(id, name, type) VALUES (387, "Last Resort", "normal");
INSERT INTO attack(id, name, type) VALUES (388, "Worry Seed", "grass");
INSERT INTO attack(id, name, type) VALUES (389, "Sucker Punch", "dark");
INSERT INTO attack(id, name, type) VALUES (390, "Toxic Spikes", "poison");
INSERT INTO attack(id, name, type) VALUES (391, "Heart Swap", "psychic");
INSERT INTO attack(id, name, type) VALUES (392, "Aqua Ring", "water");
INSERT INTO attack(id, name, type) VALUES (393, "Magnet Rise", "electric");
INSERT INTO attack(id, name, type) VALUES (394, "Flare Blitz", "fire");
INSERT INTO attack(id, name, type) VALUES (395, "Force Palm", "fighting");
INSERT INTO attack(id, name, type) VALUES (396, "Aura Sphere", "fighting");
INSERT INTO attack(id, name, type) VALUES (397, "Rock Polish", "rock");
INSERT INTO attack(id, name, type) VALUES (398, "Poison Jab", "poison");
INSERT INTO attack(id, name, type) VALUES (399, "Dark Pulse", "dark");
INSERT INTO attack(id, name, type) VALUES (400, "Night Slash", "dark");
INSERT INTO attack(id, name, type) VALUES (401, "Aqua Tail", "water");
INSERT INTO attack(id, name, type) VALUES (402, "Seed Bomb", "grass");
INSERT INTO attack(id, name, type) VALUES (403, "Air Slash", "flying");
INSERT INTO attack(id, name, type) VALUES (404, "X-Scissor", "bug");
INSERT INTO attack(id, name, type) VALUES (405, "Bug Buzz", "bug");
INSERT INTO attack(id, name, type) VALUES (406, "Dragon Pulse", "dragon");
INSERT INTO attack(id, name, type) VALUES (407, "Dragon Rush", "dragon");
INSERT INTO attack(id, name, type) VALUES (408, "Power Gem", "rock");
INSERT INTO attack(id, name, type) VALUES (409, "Drain Punch", "fighting");
INSERT INTO attack(id, name, type) VALUES (410, "Vacuum Wave", "fighting");
INSERT INTO attack(id, name, type) VALUES (411, "Focus Blast", "fighting");
INSERT INTO attack(id, name, type) VALUES (412, "Energy Ball", "grass");
INSERT INTO attack(id, name, type) VALUES (413, "Brave Bird", "flying");
INSERT INTO attack(id, name, type) VALUES (414, "Earth Power", "ground");
INSERT INTO attack(id, name, type) VALUES (415, "Switcheroo", "dark");
INSERT INTO attack(id, name, type) VALUES (416, "Giga Impact", "normal");
INSERT INTO attack(id, name, type) VALUES (417, "Nasty Plot", "dark");
INSERT INTO attack(id, name, type) VALUES (418, "Bullet Punch", "steel");
INSERT INTO attack(id, name, type) VALUES (419, "Avalanche", "ice");
INSERT INTO attack(id, name, type) VALUES (420, "Ice Shard", "ice");
INSERT INTO attack(id, name, type) VALUES (421, "Shadow Claw", "ghost");
INSERT INTO attack(id, name, type) VALUES (422, "Thunder Fang", "electric");
INSERT INTO attack(id, name, type) VALUES (423, "Ice Fang", "ice");
INSERT INTO attack(id, name, type) VALUES (424, "Fire Fang", "fire");
INSERT INTO attack(id, name, type) VALUES (425, "Shadow Sneak", "ghost");
INSERT INTO attack(id, name, type) VALUES (426, "Mud Bomb", "ground");
INSERT INTO attack(id, name, type) VALUES (427, "Psycho Cut", "psychic");
INSERT INTO attack(id, name, type) VALUES (428, "Zen Headbutt", "psychic");
INSERT INTO attack(id, name, type) VALUES (429, "Mirror Shot", "steel");
INSERT INTO attack(id, name, type) VALUES (430, "Flash Cannon", "steel");
INSERT INTO attack(id, name, type) VALUES (431, "Rock Climb", "normal");
INSERT INTO attack(id, name, type) VALUES (432, "Defog", "flying");
INSERT INTO attack(id, name, type) VALUES (433, "Trick Room", "psychic");
INSERT INTO attack(id, name, type) VALUES (434, "Draco Meteor", "dragon");
INSERT INTO attack(id, name, type) VALUES (435, "Discharge", "electric");
INSERT INTO attack(id, name, type) VALUES (436, "Lava Plume", "fire");
INSERT INTO attack(id, name, type) VALUES (437, "Leaf Storm", "grass");
INSERT INTO attack(id, name, type) VALUES (438, "Power Whip", "grass");
INSERT INTO attack(id, name, type) VALUES (439, "Rock Wrecker", "rock");
INSERT INTO attack(id, name, type) VALUES (440, "Cross Poison", "poison");
INSERT INTO attack(id, name, type) VALUES (441, "Gunk Shot", "poison");
INSERT INTO attack(id, name, type) VALUES (442, "Iron Head", "steel");
INSERT INTO attack(id, name, type) VALUES (443, "Magnet Bomb", "steel");
INSERT INTO attack(id, name, type) VALUES (444, "Stone Edge", "rock");
INSERT INTO attack(id, name, type) VALUES (445, "Captivate", "normal");
INSERT INTO attack(id, name, type) VALUES (446, "Stealth Rock", "rock");
INSERT INTO attack(id, name, type) VALUES (447, "Grass Knot", "grass");
INSERT INTO attack(id, name, type) VALUES (448, "Chatter", "flying");
INSERT INTO attack(id, name, type) VALUES (449, "Judgment", "normal");
INSERT INTO attack(id, name, type) VALUES (450, "Bug Bite", "bug");
INSERT INTO attack(id, name, type) VALUES (451, "Charge Beam", "electric");
INSERT INTO attack(id, name, type) VALUES (452, "Wood Hammer", "grass");
INSERT INTO attack(id, name, type) VALUES (453, "Aqua Jet", "water");
INSERT INTO attack(id, name, type) VALUES (454, "Attack Order", "bug");
INSERT INTO attack(id, name, type) VALUES (455, "Defend Order", "bug");
INSERT INTO attack(id, name, type) VALUES (456, "Heal Order", "bug");
INSERT INTO attack(id, name, type) VALUES (457, "Head Smash", "rock");
INSERT INTO attack(id, name, type) VALUES (458, "Double Hit", "normal");
INSERT INTO attack(id, name, type) VALUES (459, "Roar of Time", "dragon");
INSERT INTO attack(id, name, type) VALUES (460, "Spacial Rend", "dragon");
INSERT INTO attack(id, name, type) VALUES (461, "Lunar Dance", "psychic");
INSERT INTO attack(id, name, type) VALUES (462, "Crush Grip", "normal");
INSERT INTO attack(id, name, type) VALUES (463, "Magma Storm", "fire");
INSERT INTO attack(id, name, type) VALUES (464, "Dark Void", "dark");
INSERT INTO attack(id, name, type) VALUES (465, "Seed Flare", "grass");
INSERT INTO attack(id, name, type) VALUES (466, "Ominous Wind", "ghost");
INSERT INTO attack(id, name, type) VALUES (467, "Shadow Force", "ghost");
INSERT INTO attack(id, name, type) VALUES (468, "Hone Claws", "dark");
INSERT INTO attack(id, name, type) VALUES (469, "Wide Guard", "rock");
INSERT INTO attack(id, name, type) VALUES (470, "Guard Split", "psychic");
INSERT INTO attack(id, name, type) VALUES (471, "Power Split", "psychic");
INSERT INTO attack(id, name, type) VALUES (472, "Wonder Room", "psychic");
INSERT INTO attack(id, name, type) VALUES (473, "Psyshock", "psychic");
INSERT INTO attack(id, name, type) VALUES (474, "Venoshock", "poison");
INSERT INTO attack(id, name, type) VALUES (475, "Autotomize", "steel");
INSERT INTO attack(id, name, type) VALUES (476, "Rage Powder", "bug");
INSERT INTO attack(id, name, type) VALUES (477, "Telekinesis", "psychic");
INSERT INTO attack(id, name, type) VALUES (478, "Magic Room", "psychic");
INSERT INTO attack(id, name, type) VALUES (479, "Smack Down", "rock");
INSERT INTO attack(id, name, type) VALUES (480, "Storm Throw", "fighting");
INSERT INTO attack(id, name, type) VALUES (481, "Flame Burst", "fire");
INSERT INTO attack(id, name, type) VALUES (482, "Sludge Wave", "poison");
INSERT INTO attack(id, name, type) VALUES (483, "Quiver Dance", "bug");
INSERT INTO attack(id, name, type) VALUES (484, "Heavy Slam", "steel");
INSERT INTO attack(id, name, type) VALUES (485, "Synchronoise", "psychic");
INSERT INTO attack(id, name, type) VALUES (486, "Electro Ball", "electric");
INSERT INTO attack(id, name, type) VALUES (487, "Soak", "water");
INSERT INTO attack(id, name, type) VALUES (488, "Flame Charge", "fire");
INSERT INTO attack(id, name, type) VALUES (489, "Coil", "poison");
INSERT INTO attack(id, name, type) VALUES (490, "Low Sweep", "fighting");
INSERT INTO attack(id, name, type) VALUES (491, "Acid Spray", "poison");
INSERT INTO attack(id, name, type) VALUES (492, "Foul Play", "dark");
INSERT INTO attack(id, name, type) VALUES (493, "Simple Beam", "normal");
INSERT INTO attack(id, name, type) VALUES (494, "Entrainment", "normal");
INSERT INTO attack(id, name, type) VALUES (495, "After You", "normal");
INSERT INTO attack(id, name, type) VALUES (496, "Round", "normal");
INSERT INTO attack(id, name, type) VALUES (497, "Echoed Voice", "normal");
INSERT INTO attack(id, name, type) VALUES (498, "Chip Away", "normal");
INSERT INTO attack(id, name, type) VALUES (499, "Clear Smog", "poison");
INSERT INTO attack(id, name, type) VALUES (500, "Stored Power", "psychic");
INSERT INTO attack(id, name, type) VALUES (501, "Quick Guard", "fighting");
INSERT INTO attack(id, name, type) VALUES (502, "Ally Switch", "psychic");
INSERT INTO attack(id, name, type) VALUES (503, "Scald", "water");
INSERT INTO attack(id, name, type) VALUES (504, "Shell Smash", "normal");
INSERT INTO attack(id, name, type) VALUES (505, "Heal Pulse", "psychic");
INSERT INTO attack(id, name, type) VALUES (506, "Hex", "ghost");
INSERT INTO attack(id, name, type) VALUES (507, "Sky Drop", "flying");
INSERT INTO attack(id, name, type) VALUES (508, "Shift Gear", "steel");
INSERT INTO attack(id, name, type) VALUES (509, "Circle Throw", "fighting");
INSERT INTO attack(id, name, type) VALUES (510, "Incinerate", "fire");
INSERT INTO attack(id, name, type) VALUES (511, "Quash", "dark");
INSERT INTO attack(id, name, type) VALUES (512, "Acrobatics", "flying");
INSERT INTO attack(id, name, type) VALUES (513, "Reflect Type", "normal");
INSERT INTO attack(id, name, type) VALUES (514, "Retaliate", "normal");
INSERT INTO attack(id, name, type) VALUES (515, "Final Gambit", "fighting");
INSERT INTO attack(id, name, type) VALUES (516, "Bestow", "normal");
INSERT INTO attack(id, name, type) VALUES (517, "Inferno", "fire");
INSERT INTO attack(id, name, type) VALUES (518, "Water Pledge", "water");
INSERT INTO attack(id, name, type) VALUES (519, "Fire Pledge", "fire");
INSERT INTO attack(id, name, type) VALUES (520, "Grass Pledge", "grass");
INSERT INTO attack(id, name, type) VALUES (521, "Volt Switch", "electric");
INSERT INTO attack(id, name, type) VALUES (522, "Struggle Bug", "bug");
INSERT INTO attack(id, name, type) VALUES (523, "Bulldoze", "ground");
INSERT INTO attack(id, name, type) VALUES (524, "Frost Breath", "ice");
INSERT INTO attack(id, name, type) VALUES (525, "Dragon Tail", "dragon");
INSERT INTO attack(id, name, type) VALUES (526, "Work Up", "normal");
INSERT INTO attack(id, name, type) VALUES (527, "Electroweb", "electric");
INSERT INTO attack(id, name, type) VALUES (528, "Wild Charge", "electric");
INSERT INTO attack(id, name, type) VALUES (529, "Drill Run", "ground");
INSERT INTO attack(id, name, type) VALUES (530, "Dual Chop", "dragon");
INSERT INTO attack(id, name, type) VALUES (531, "Heart Stamp", "psychic");
INSERT INTO attack(id, name, type) VALUES (532, "Horn Leech", "grass");
INSERT INTO attack(id, name, type) VALUES (533, "Sacred Sword", "fighting");
INSERT INTO attack(id, name, type) VALUES (534, "Razor Shell", "water");
INSERT INTO attack(id, name, type) VALUES (535, "Heat Crash", "fire");
INSERT INTO attack(id, name, type) VALUES (536, "Leaf Tornado", "grass");
INSERT INTO attack(id, name, type) VALUES (537, "Steamroller", "bug");
INSERT INTO attack(id, name, type) VALUES (538, "Cotton Guard", "grass");
INSERT INTO attack(id, name, type) VALUES (539, "Night Daze", "dark");
INSERT INTO attack(id, name, type) VALUES (540, "Psystrike", "psychic");
INSERT INTO attack(id, name, type) VALUES (541, "Tail Slap", "normal");
INSERT INTO attack(id, name, type) VALUES (542, "Hurricane", "flying");
INSERT INTO attack(id, name, type) VALUES (543, "Head Charge", "normal");
INSERT INTO attack(id, name, type) VALUES (544, "Gear Grind", "steel");
INSERT INTO attack(id, name, type) VALUES (545, "Searing Shot", "fire");
INSERT INTO attack(id, name, type) VALUES (546, "Techno Blast", "normal");
INSERT INTO attack(id, name, type) VALUES (547, "Relic Song", "normal");
INSERT INTO attack(id, name, type) VALUES (548, "Secret Sword", "fighting");
INSERT INTO attack(id, name, type) VALUES (549, "Glaciate", "ice");
INSERT INTO attack(id, name, type) VALUES (550, "Bolt Strike", "electric");
INSERT INTO attack(id, name, type) VALUES (551, "Blue Flare", "fire");
INSERT INTO attack(id, name, type) VALUES (552, "Fiery Dance", "fire");
INSERT INTO attack(id, name, type) VALUES (553, "Freeze Shock", "ice");
INSERT INTO attack(id, name, type) VALUES (554, "Ice Burn", "ice");
INSERT INTO attack(id, name, type) VALUES (555, "Snarl", "dark");
INSERT INTO attack(id, name, type) VALUES (556, "Icicle Crash", "ice");
INSERT INTO attack(id, name, type) VALUES (557, "V-create", "fire");
INSERT INTO attack(id, name, type) VALUES (558, "Fusion Flare", "fire");
INSERT INTO attack(id, name, type) VALUES (559, "Fusion Bolt", "electric");
INSERT INTO attack(id, name, type) VALUES (560, "Flying Press", "fighting");
INSERT INTO attack(id, name, type) VALUES (561, "Mat Block", "fighting");
INSERT INTO attack(id, name, type) VALUES (562, "Belch", "poison");
INSERT INTO attack(id, name, type) VALUES (563, "Rototiller", "ground");
INSERT INTO attack(id, name, type) VALUES (564, "Sticky Web", "bug");
INSERT INTO attack(id, name, type) VALUES (565, "Fell Stinger", "bug");
INSERT INTO attack(id, name, type) VALUES (566, "Phantom Force", "ghost");
INSERT INTO attack(id, name, type) VALUES (567, "Trick-or-Treat", "ghost");
INSERT INTO attack(id, name, type) VALUES (568, "Noble Roar", "normal");
INSERT INTO attack(id, name, type) VALUES (569, "Ion Deluge", "electric");
INSERT INTO attack(id, name, type) VALUES (570, "Parabolic Charge", "electric");
INSERT INTO attack(id, name, type) VALUES (571, "Forest�s Curse", "grass");
INSERT INTO attack(id, name, type) VALUES (572, "Petal Blizzard", "grass");
INSERT INTO attack(id, name, type) VALUES (573, "Freeze-Dry", "ice");
INSERT INTO attack(id, name, type) VALUES (574, "Disarming Voice", "fairy");
INSERT INTO attack(id, name, type) VALUES (575, "Parting Shot", "dark");
INSERT INTO attack(id, name, type) VALUES (576, "Topsy-Turvy", "dark");
INSERT INTO attack(id, name, type) VALUES (577, "Draining Kiss", "fairy");
INSERT INTO attack(id, name, type) VALUES (578, "Crafty Shield", "fairy");
INSERT INTO attack(id, name, type) VALUES (579, "Flower Shield", "fairy");
INSERT INTO attack(id, name, type) VALUES (580, "Grassy Terrain", "grass");
INSERT INTO attack(id, name, type) VALUES (581, "Misty Terrain", "fairy");
INSERT INTO attack(id, name, type) VALUES (582, "Electrify", "electric");
INSERT INTO attack(id, name, type) VALUES (583, "Play Rough", "fairy");
INSERT INTO attack(id, name, type) VALUES (584, "Fairy Wind", "fairy");
INSERT INTO attack(id, name, type) VALUES (585, "Moonblast", "fairy");
INSERT INTO attack(id, name, type) VALUES (586, "Boomburst", "normal");
INSERT INTO attack(id, name, type) VALUES (587, "Fairy Lock", "fairy");
INSERT INTO attack(id, name, type) VALUES (588, "King�s Shield", "steel");
INSERT INTO attack(id, name, type) VALUES (589, "Play Nice", "normal");
INSERT INTO attack(id, name, type) VALUES (590, "Confide", "normal");
INSERT INTO attack(id, name, type) VALUES (591, "Diamond Storm", "rock");
INSERT INTO attack(id, name, type) VALUES (592, "Steam Eruption", "water");
INSERT INTO attack(id, name, type) VALUES (593, "Hyperspace Hole", "psychic");
INSERT INTO attack(id, name, type) VALUES (594, "Water Shuriken", "water");
INSERT INTO attack(id, name, type) VALUES (595, "Mystical Fire", "fire");
INSERT INTO attack(id, name, type) VALUES (596, "Spiky Shield", "grass");
INSERT INTO attack(id, name, type) VALUES (597, "Aromatic Mist", "fairy");
INSERT INTO attack(id, name, type) VALUES (598, "Eerie Impulse", "electric");
INSERT INTO attack(id, name, type) VALUES (599, "Venom Drench", "poison");
INSERT INTO attack(id, name, type) VALUES (600, "Powder", "bug");
INSERT INTO attack(id, name, type) VALUES (601, "Geomancy", "fairy");
INSERT INTO attack(id, name, type) VALUES (602, "Magnetic Flux", "electric");
INSERT INTO attack(id, name, type) VALUES (603, "Happy Hour", "normal");
INSERT INTO attack(id, name, type) VALUES (604, "Electric Terrain", "electric");
INSERT INTO attack(id, name, type) VALUES (605, "Dazzling Gleam", "fairy");
INSERT INTO attack(id, name, type) VALUES (606, "Celebrate", "normal");
INSERT INTO attack(id, name, type) VALUES (607, "Hold Hands", "normal");
INSERT INTO attack(id, name, type) VALUES (608, "Baby-Doll Eyes", "fairy");
INSERT INTO attack(id, name, type) VALUES (609, "Nuzzle", "electric");
INSERT INTO attack(id, name, type) VALUES (610, "Hold Back", "normal");
INSERT INTO attack(id, name, type) VALUES (611, "Infestation", "bug");
INSERT INTO attack(id, name, type) VALUES (612, "Power-Up Punch", "fighting");
INSERT INTO attack(id, name, type) VALUES (613, "Oblivion Wing", "flying");
INSERT INTO attack(id, name, type) VALUES (614, "Thousand Arrows", "ground");
INSERT INTO attack(id, name, type) VALUES (615, "Thousand Waves", "ground");
INSERT INTO attack(id, name, type) VALUES (616, "Land�s Wrath", "ground");
INSERT INTO attack(id, name, type) VALUES (617, "Light of Ruin", "fairy");
INSERT INTO attack(id, name, type) VALUES (618, "Origin Pulse", "water");
INSERT INTO attack(id, name, type) VALUES (619, "Precipice Blades", "ground");
INSERT INTO attack(id, name, type) VALUES (620, "Dragon Ascent", "flying");
INSERT INTO attack(id, name, type) VALUES (621, "Hyperspace Fury", "dark");
INSERT INTO attack(id, name, type) VALUES (622, "Breakneck Blitz", "normal");
INSERT INTO attack(id, name, type) VALUES (623, "Breakneck Blitz", "normal");
INSERT INTO attack(id, name, type) VALUES (624, "All-Out Pummeling", "fighting");
INSERT INTO attack(id, name, type) VALUES (625, "All-Out Pummeling", "fighting");
INSERT INTO attack(id, name, type) VALUES (626, "Supersonic Skystrike", "flying");
INSERT INTO attack(id, name, type) VALUES (627, "Supersonic Skystrike", "flying");
INSERT INTO attack(id, name, type) VALUES (628, "Acid Downpour", "poison");
INSERT INTO attack(id, name, type) VALUES (629, "Acid Downpour", "poison");
INSERT INTO attack(id, name, type) VALUES (630, "Tectonic Rage", "ground");
INSERT INTO attack(id, name, type) VALUES (631, "Tectonic Rage", "ground");
INSERT INTO attack(id, name, type) VALUES (632, "Continental Crush", "rock");
INSERT INTO attack(id, name, type) VALUES (633, "Continental Crush", "rock");
INSERT INTO attack(id, name, type) VALUES (634, "Savage Spin-Out", "bug");
INSERT INTO attack(id, name, type) VALUES (635, "Savage Spin-Out", "bug");
INSERT INTO attack(id, name, type) VALUES (636, "Never-Ending Nightmare", "ghost");
INSERT INTO attack(id, name, type) VALUES (637, "Never-Ending Nightmare", "ghost");
INSERT INTO attack(id, name, type) VALUES (638, "Corkscrew Crash", "steel");
INSERT INTO attack(id, name, type) VALUES (639, "Corkscrew Crash", "steel");
INSERT INTO attack(id, name, type) VALUES (640, "Inferno Overdrive", "fire");
INSERT INTO attack(id, name, type) VALUES (641, "Inferno Overdrive", "fire");
INSERT INTO attack(id, name, type) VALUES (642, "Hydro Vortex", "water");
INSERT INTO attack(id, name, type) VALUES (643, "Hydro Vortex", "water");
INSERT INTO attack(id, name, type) VALUES (644, "Bloom Doom", "grass");
INSERT INTO attack(id, name, type) VALUES (645, "Bloom Doom", "grass");
INSERT INTO attack(id, name, type) VALUES (646, "Gigavolt Havoc", "electric");
INSERT INTO attack(id, name, type) VALUES (647, "Gigavolt Havoc", "electric");
INSERT INTO attack(id, name, type) VALUES (648, "Shattered Psyche", "psychic");
INSERT INTO attack(id, name, type) VALUES (649, "Shattered Psyche", "psychic");
INSERT INTO attack(id, name, type) VALUES (650, "Subzero Slammer", "ice");
INSERT INTO attack(id, name, type) VALUES (651, "Subzero Slammer", "ice");
INSERT INTO attack(id, name, type) VALUES (652, "Devastating Drake", "dragon");
INSERT INTO attack(id, name, type) VALUES (653, "Devastating Drake", "dragon");
INSERT INTO attack(id, name, type) VALUES (654, "Black Hole Eclipse", "dark");
INSERT INTO attack(id, name, type) VALUES (655, "Black Hole Eclipse", "dark");
INSERT INTO attack(id, name, type) VALUES (656, "Twinkle Tackle", "fairy");
INSERT INTO attack(id, name, type) VALUES (657, "Twinkle Tackle", "fairy");
INSERT INTO attack(id, name, type) VALUES (658, "Catastropika", "electric");
INSERT INTO attack(id, name, type) VALUES (659, "Shore Up", "ground");
INSERT INTO attack(id, name, type) VALUES (660, "First Impression", "bug");
INSERT INTO attack(id, name, type) VALUES (661, "Baneful Bunker", "poison");
INSERT INTO attack(id, name, type) VALUES (662, "Spirit Shackle", "ghost");
INSERT INTO attack(id, name, type) VALUES (663, "Darkest Lariat", "dark");
INSERT INTO attack(id, name, type) VALUES (664, "Sparkling Aria", "water");
INSERT INTO attack(id, name, type) VALUES (665, "Ice Hammer", "ice");
INSERT INTO attack(id, name, type) VALUES (666, "Floral Healing", "fairy");
INSERT INTO attack(id, name, type) VALUES (667, "High Horsepower", "ground");
INSERT INTO attack(id, name, type) VALUES (668, "Strength Sap", "grass");
INSERT INTO attack(id, name, type) VALUES (669, "Solar Blade", "grass");
INSERT INTO attack(id, name, type) VALUES (670, "Leafage", "grass");
INSERT INTO attack(id, name, type) VALUES (671, "Spotlight", "normal");
INSERT INTO attack(id, name, type) VALUES (672, "Toxic Thread", "poison");
INSERT INTO attack(id, name, type) VALUES (673, "Laser Focus", "normal");
INSERT INTO attack(id, name, type) VALUES (674, "Gear Up", "steel");
INSERT INTO attack(id, name, type) VALUES (675, "Throat Chop", "dark");
INSERT INTO attack(id, name, type) VALUES (676, "Pollen Puff", "bug");
INSERT INTO attack(id, name, type) VALUES (677, "Anchor Shot", "steel");
INSERT INTO attack(id, name, type) VALUES (678, "Psychic Terrain", "psychic");
INSERT INTO attack(id, name, type) VALUES (679, "Lunge", "bug");
INSERT INTO attack(id, name, type) VALUES (680, "Fire Lash", "fire");
INSERT INTO attack(id, name, type) VALUES (681, "Power Trip", "dark");
INSERT INTO attack(id, name, type) VALUES (682, "Burn Up", "fire");
INSERT INTO attack(id, name, type) VALUES (683, "Speed Swap", "psychic");
INSERT INTO attack(id, name, type) VALUES (684, "Smart Strike", "steel");
INSERT INTO attack(id, name, type) VALUES (685, "Purify", "poison");
INSERT INTO attack(id, name, type) VALUES (686, "Revelation Dance", "normal");
INSERT INTO attack(id, name, type) VALUES (687, "Core Enforcer", "dragon");
INSERT INTO attack(id, name, type) VALUES (688, "Trop Kick", "grass");
INSERT INTO attack(id, name, type) VALUES (689, "Instruct", "psychic");
INSERT INTO attack(id, name, type) VALUES (690, "Beak Blast", "flying");
INSERT INTO attack(id, name, type) VALUES (691, "Clanging Scales", "dragon");
INSERT INTO attack(id, name, type) VALUES (692, "Dragon Hammer", "dragon");
INSERT INTO attack(id, name, type) VALUES (693, "Brutal Swing", "dark");
INSERT INTO attack(id, name, type) VALUES (694, "Aurora Veil", "ice");
INSERT INTO attack(id, name, type) VALUES (695, "Sinister Arrow Raid", "ghost");
INSERT INTO attack(id, name, type) VALUES (696, "Malicious Moonsault", "dark");
INSERT INTO attack(id, name, type) VALUES (697, "Oceanic Operetta", "water");
INSERT INTO attack(id, name, type) VALUES (698, "Guardian of Alola", "fairy");
INSERT INTO attack(id, name, type) VALUES (699, "Soul-Stealing 7-Star Strike", "ghost");
INSERT INTO attack(id, name, type) VALUES (700, "Stoked Sparksurfer", "electric");
INSERT INTO attack(id, name, type) VALUES (701, "Pulverizing Pancake", "normal");
INSERT INTO attack(id, name, type) VALUES (702, "Extreme Evoboost", "normal");
INSERT INTO attack(id, name, type) VALUES (703, "Genesis Supernova", "psychic");
INSERT INTO attack(id, name, type) VALUES (704, "Shell Trap", "fire");
INSERT INTO attack(id, name, type) VALUES (705, "Fleur Cannon", "fairy");
INSERT INTO attack(id, name, type) VALUES (706, "Psychic Fangs", "psychic");
INSERT INTO attack(id, name, type) VALUES (707, "Stomping Tantrum", "ground");
INSERT INTO attack(id, name, type) VALUES (708, "Shadow Bone", "ghost");
INSERT INTO attack(id, name, type) VALUES (709, "Accelerock", "rock");
INSERT INTO attack(id, name, type) VALUES (710, "Liquidation", "water");
INSERT INTO attack(id, name, type) VALUES (711, "Prismatic Laser", "psychic");
INSERT INTO attack(id, name, type) VALUES (712, "Spectral Thief", "ghost");
INSERT INTO attack(id, name, type) VALUES (713, "Sunsteel Strike", "steel");
INSERT INTO attack(id, name, type) VALUES (714, "Moongeist Beam", "ghost");
INSERT INTO attack(id, name, type) VALUES (715, "Tearful Look", "normal");
INSERT INTO attack(id, name, type) VALUES (716, "Zing Zap", "electric");
INSERT INTO attack(id, name, type) VALUES (717, "Nature�s Madness", "fairy");
INSERT INTO attack(id, name, type) VALUES (718, "Multi-Attack", "normal");
INSERT INTO attack(id, name, type) VALUES (719, "10,000,000 Volt Thunderbolt", "electric");
INSERT INTO attack(id, name, type) VALUES (720, "Mind Blown", "fire");
INSERT INTO attack(id, name, type) VALUES (721, "Plasma Fists", "electric");
INSERT INTO attack(id, name, type) VALUES (722, "Photon Geyser", "psychic");
INSERT INTO attack(id, name, type) VALUES (723, "Light That Burns the Sky", "psychic");
INSERT INTO attack(id, name, type) VALUES (724, "Searing Sunraze Smash", "steel");
INSERT INTO attack(id, name, type) VALUES (725, "Menacing Moonraze Maelstrom", "ghost");
INSERT INTO attack(id, name, type) VALUES (726, "Let�s Snuggle Forever", "fairy");
INSERT INTO attack(id, name, type) VALUES (727, "Splintered Stormshards", "rock");
INSERT INTO attack(id, name, type) VALUES (728, "Clangorous Soulblaze", "dragon");
INSERT INTO attack(id, name, type) VALUES (729, "Zippy Zap", "electric");
INSERT INTO attack(id, name, type) VALUES (730, "Splishy Splash", "water");
INSERT INTO attack(id, name, type) VALUES (731, "Floaty Fall", "flying");
INSERT INTO attack(id, name, type) VALUES (732, "Pika Papow", "electric");
INSERT INTO attack(id, name, type) VALUES (733, "Bouncy Bubble", "water");
INSERT INTO attack(id, name, type) VALUES (734, "Buzzy Buzz", "electric");
INSERT INTO attack(id, name, type) VALUES (735, "Sizzly Slide", "fire");
INSERT INTO attack(id, name, type) VALUES (736, "Glitzy Glow", "psychic");
INSERT INTO attack(id, name, type) VALUES (737, "Baddy Bad", "dark");
INSERT INTO attack(id, name, type) VALUES (738, "Sappy Seed", "grass");
INSERT INTO attack(id, name, type) VALUES (739, "Freezy Frost", "ice");
INSERT INTO attack(id, name, type) VALUES (740, "Sparkly Swirl", "fairy");
INSERT INTO attack(id, name, type) VALUES (741, "Veevee Volley", "normal");
INSERT INTO attack(id, name, type) VALUES (742, "Double Iron Bash", "steel");
INSERT INTO attack(id, name, type) VALUES (743, "Max Guard", "normal");
INSERT INTO attack(id, name, type) VALUES (744, "Dynamax Cannon", "dragon");
INSERT INTO attack(id, name, type) VALUES (745, "Snipe Shot", "water");
INSERT INTO attack(id, name, type) VALUES (746, "Jaw Lock", "dark");
INSERT INTO attack(id, name, type) VALUES (747, "Stuff Cheeks", "normal");
INSERT INTO attack(id, name, type) VALUES (748, "No Retreat", "fighting");
INSERT INTO attack(id, name, type) VALUES (749, "Tar Shot", "rock");
INSERT INTO attack(id, name, type) VALUES (750, "Magic Powder", "psychic");
INSERT INTO attack(id, name, type) VALUES (751, "Dragon Darts", "dragon");
INSERT INTO attack(id, name, type) VALUES (752, "Teatime", "normal");
INSERT INTO attack(id, name, type) VALUES (753, "Octolock", "fighting");
INSERT INTO attack(id, name, type) VALUES (754, "Bolt Beak", "electric");
INSERT INTO attack(id, name, type) VALUES (755, "Fishious Rend", "water");
INSERT INTO attack(id, name, type) VALUES (756, "Court Change", "normal");
INSERT INTO attack(id, name, type) VALUES (757, "Max Flare", "fire");
INSERT INTO attack(id, name, type) VALUES (758, "Max Flutterby", "bug");
INSERT INTO attack(id, name, type) VALUES (759, "Max Lightning", "electric");
INSERT INTO attack(id, name, type) VALUES (760, "Max Strike", "normal");
INSERT INTO attack(id, name, type) VALUES (761, "Max Knuckle", "fighting");
INSERT INTO attack(id, name, type) VALUES (762, "Max Phantasm", "ghost");
INSERT INTO attack(id, name, type) VALUES (763, "Max Hailstorm", "ice");
INSERT INTO attack(id, name, type) VALUES (764, "Max Ooze", "poison");
INSERT INTO attack(id, name, type) VALUES (765, "Max Geyser", "water");
INSERT INTO attack(id, name, type) VALUES (766, "Max Airstream", "flying");
INSERT INTO attack(id, name, type) VALUES (767, "Max Starfall", "fairy");
INSERT INTO attack(id, name, type) VALUES (768, "Max Wyrmwind", "dragon");
INSERT INTO attack(id, name, type) VALUES (769, "Max Mindstorm", "psychic");
INSERT INTO attack(id, name, type) VALUES (770, "Max Rockfall", "rock");
INSERT INTO attack(id, name, type) VALUES (771, "Max Quake", "ground");
INSERT INTO attack(id, name, type) VALUES (772, "Max Darkness", "dark");
INSERT INTO attack(id, name, type) VALUES (773, "Max Overgrowth", "grass");
INSERT INTO attack(id, name, type) VALUES (774, "Max Steelspike", "steel");
INSERT INTO attack(id, name, type) VALUES (775, "Clangorous Soul", "dragon");
INSERT INTO attack(id, name, type) VALUES (776, "Body Press", "fighting");
INSERT INTO attack(id, name, type) VALUES (777, "Decorate", "fairy");
INSERT INTO attack(id, name, type) VALUES (778, "Drum Beating", "grass");
INSERT INTO attack(id, name, type) VALUES (779, "Snap Trap", "grass");
INSERT INTO attack(id, name, type) VALUES (780, "Pyro Ball", "fire");
INSERT INTO attack(id, name, type) VALUES (781, "Behemoth Blade", "steel");
INSERT INTO attack(id, name, type) VALUES (782, "Behemoth Bash", "steel");
INSERT INTO attack(id, name, type) VALUES (783, "Aura Wheel", "electric");
INSERT INTO attack(id, name, type) VALUES (784, "Breaking Swipe", "dragon");
INSERT INTO attack(id, name, type) VALUES (785, "Branch Poke", "grass");
INSERT INTO attack(id, name, type) VALUES (786, "Overdrive", "electric");
INSERT INTO attack(id, name, type) VALUES (787, "Apple Acid", "grass");
INSERT INTO attack(id, name, type) VALUES (788, "Grav Apple", "grass");
INSERT INTO attack(id, name, type) VALUES (789, "Spirit Break", "fairy");
INSERT INTO attack(id, name, type) VALUES (790, "Strange Steam", "fairy");
INSERT INTO attack(id, name, type) VALUES (791, "Life Dew", "water");
INSERT INTO attack(id, name, type) VALUES (792, "Obstruct", "dark");
INSERT INTO attack(id, name, type) VALUES (793, "False Surrender", "dark");
INSERT INTO attack(id, name, type) VALUES (794, "Meteor Assault", "fighting");
INSERT INTO attack(id, name, type) VALUES (795, "Eternabeam", "dragon");
INSERT INTO attack(id, name, type) VALUES (796, "Steel Beam", "steel");
INSERT INTO attack(id, name, type) VALUES (797, "Expanding Force", "psychic");
INSERT INTO attack(id, name, type) VALUES (798, "Steel Roller", "steel");
INSERT INTO attack(id, name, type) VALUES (799, "Scale Shot", "dragon");
INSERT INTO attack(id, name, type) VALUES (800, "Meteor Beam", "rock");
INSERT INTO attack(id, name, type) VALUES (801, "Shell Side Arm", "poison");
INSERT INTO attack(id, name, type) VALUES (802, "Misty Explosion", "fairy");
INSERT INTO attack(id, name, type) VALUES (803, "Grassy Glide", "grass");
INSERT INTO attack(id, name, type) VALUES (804, "Rising Voltage", "electric");
INSERT INTO attack(id, name, type) VALUES (805, "Terrain Pulse", "normal");
INSERT INTO attack(id, name, type) VALUES (806, "Skitter Smack", "bug");
INSERT INTO attack(id, name, type) VALUES (807, "Burning Jealousy", "fire");
INSERT INTO attack(id, name, type) VALUES (808, "Lash Out", "dark");
INSERT INTO attack(id, name, type) VALUES (809, "Poltergeist", "ghost");
INSERT INTO attack(id, name, type) VALUES (810, "Corrosive Gas", "poison");
INSERT INTO attack(id, name, type) VALUES (811, "Coaching", "fighting");
INSERT INTO attack(id, name, type) VALUES (812, "Flip Turn", "water");
INSERT INTO attack(id, name, type) VALUES (813, "Triple Axel", "ice");
INSERT INTO attack(id, name, type) VALUES (814, "Dual Wingbeat", "flying");
INSERT INTO attack(id, name, type) VALUES (815, "Scorching Sands", "ground");
INSERT INTO attack(id, name, type) VALUES (816, "Jungle Healing", "grass");
INSERT INTO attack(id, name, type) VALUES (817, "Wicked Blow", "dark");
INSERT INTO attack(id, name, type) VALUES (818, "Surging Strikes", "water");
INSERT INTO attack(id, name, type) VALUES (819, "Thunder Cage", "electric");
INSERT INTO attack(id, name, type) VALUES (820, "Dragon Energy", "dragon");
INSERT INTO attack(id, name, type) VALUES (821, "Freezing Glare", "psychic");
INSERT INTO attack(id, name, type) VALUES (822, "Fiery Wrath", "dark");
INSERT INTO attack(id, name, type) VALUES (823, "Thunderous Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (824, "Glacial Lance", "ice");
INSERT INTO attack(id, name, type) VALUES (825, "Astral Barrage", "ghost");
INSERT INTO attack(id, name, type) VALUES (826, "Eerie Spell", "psychic");
INSERT INTO attack(id, name, type) VALUES (827, "Dire Claw", "poison");
INSERT INTO attack(id, name, type) VALUES (828, "Psyshield Bash", "psychic");
INSERT INTO attack(id, name, type) VALUES (829, "Power Shift", "normal");
INSERT INTO attack(id, name, type) VALUES (830, "Stone Axe", "rock");
INSERT INTO attack(id, name, type) VALUES (831, "Springtide Storm", "fairy");
INSERT INTO attack(id, name, type) VALUES (832, "Mystical Power", "psychic");
INSERT INTO attack(id, name, type) VALUES (833, "Raging Fury", "fire");
INSERT INTO attack(id, name, type) VALUES (834, "Wave Crash", "water");
INSERT INTO attack(id, name, type) VALUES (835, "Chloroblast", "grass");
INSERT INTO attack(id, name, type) VALUES (836, "Mountain Gale", "ice");
INSERT INTO attack(id, name, type) VALUES (837, "Victory Dance", "fighting");
INSERT INTO attack(id, name, type) VALUES (838, "Headlong Rush", "ground");
INSERT INTO attack(id, name, type) VALUES (839, "Barb Barrage", "poison");
INSERT INTO attack(id, name, type) VALUES (840, "Esper Wing", "psychic");
INSERT INTO attack(id, name, type) VALUES (841, "Bitter Malice", "ghost");
INSERT INTO attack(id, name, type) VALUES (842, "Shelter", "steel");
INSERT INTO attack(id, name, type) VALUES (843, "Triple Arrows", "fighting");
INSERT INTO attack(id, name, type) VALUES (844, "Infernal Parade", "ghost");
INSERT INTO attack(id, name, type) VALUES (845, "Ceaseless Edge", "dark");
INSERT INTO attack(id, name, type) VALUES (846, "Bleakwind Storm", "flying");
INSERT INTO attack(id, name, type) VALUES (847, "Wildbolt Storm", "electric");
INSERT INTO attack(id, name, type) VALUES (848, "Sandsear Storm", "ground");
INSERT INTO attack(id, name, type) VALUES (849, "Lunar Blessing", "psychic");
INSERT INTO attack(id, name, type) VALUES (850, "Take Heart", "psychic");
INSERT INTO attack(id, name, type) VALUES (851, "Tera Blast", "normal");
INSERT INTO attack(id, name, type) VALUES (852, "Silk Trap", "bug");
INSERT INTO attack(id, name, type) VALUES (853, "Axe Kick", "fighting");
INSERT INTO attack(id, name, type) VALUES (854, "Last Respects", "ghost");
INSERT INTO attack(id, name, type) VALUES (855, "Lumina Crash", "psychic");
INSERT INTO attack(id, name, type) VALUES (856, "Order Up", "dragon");
INSERT INTO attack(id, name, type) VALUES (857, "Jet Punch", "water");
INSERT INTO attack(id, name, type) VALUES (858, "Spicy Extract", "grass");
INSERT INTO attack(id, name, type) VALUES (859, "Spin Out", "steel");
INSERT INTO attack(id, name, type) VALUES (860, "Population Bomb", "normal");
INSERT INTO attack(id, name, type) VALUES (861, "Ice Spinner", "ice");
INSERT INTO attack(id, name, type) VALUES (862, "Glaive Rush", "dragon");
INSERT INTO attack(id, name, type) VALUES (863, "Revival Blessing", "normal");
INSERT INTO attack(id, name, type) VALUES (864, "Salt Cure", "rock");
INSERT INTO attack(id, name, type) VALUES (865, "Triple Dive", "water");
INSERT INTO attack(id, name, type) VALUES (866, "Mortal Spin", "poison");
INSERT INTO attack(id, name, type) VALUES (867, "Doodle", "normal");
INSERT INTO attack(id, name, type) VALUES (868, "Fillet Away", "normal");
INSERT INTO attack(id, name, type) VALUES (869, "Kowtow Cleave", "dark");
INSERT INTO attack(id, name, type) VALUES (870, "Flower Trick", "grass");
INSERT INTO attack(id, name, type) VALUES (871, "Torch Song", "fire");
INSERT INTO attack(id, name, type) VALUES (872, "Aqua Step", "water");
INSERT INTO attack(id, name, type) VALUES (873, "Raging Bull", "normal");
INSERT INTO attack(id, name, type) VALUES (874, "Make It Rain", "steel");
INSERT INTO attack(id, name, type) VALUES (875, "Psyblade", "psychic");
INSERT INTO attack(id, name, type) VALUES (876, "Hydro Steam", "water");
INSERT INTO attack(id, name, type) VALUES (877, "Ruination", "dark");
INSERT INTO attack(id, name, type) VALUES (878, "Collision Course", "fighting");
INSERT INTO attack(id, name, type) VALUES (879, "Electro Drift", "electric");
INSERT INTO attack(id, name, type) VALUES (880, "Shed Tail", "normal");
INSERT INTO attack(id, name, type) VALUES (881, "Chilly Reception", "ice");
INSERT INTO attack(id, name, type) VALUES (882, "Tidy Up", "normal");
INSERT INTO attack(id, name, type) VALUES (883, "Snowscape", "ice");
INSERT INTO attack(id, name, type) VALUES (884, "Pounce", "bug");
INSERT INTO attack(id, name, type) VALUES (885, "Trailblaze", "grass");
INSERT INTO attack(id, name, type) VALUES (886, "Chilling Water", "water");
INSERT INTO attack(id, name, type) VALUES (887, "Hyper Drill", "normal");
INSERT INTO attack(id, name, type) VALUES (888, "Twin Beam", "psychic");
INSERT INTO attack(id, name, type) VALUES (889, "Rage Fist", "ghost");
INSERT INTO attack(id, name, type) VALUES (890, "Armor Cannon", "fire");
INSERT INTO attack(id, name, type) VALUES (891, "Bitter Blade", "fire");
INSERT INTO attack(id, name, type) VALUES (892, "Double Shock", "electric");
INSERT INTO attack(id, name, type) VALUES (893, "Gigaton Hammer", "steel");
INSERT INTO attack(id, name, type) VALUES (894, "Comeuppance", "dark");
INSERT INTO attack(id, name, type) VALUES (895, "Aqua Cutter", "water");
INSERT INTO attack(id, name, type) VALUES (896, "Blazing Torque", "fire");
INSERT INTO attack(id, name, type) VALUES (897, "Wicked Torque", "dark");
INSERT INTO attack(id, name, type) VALUES (898, "Noxious Torque", "poison");
INSERT INTO attack(id, name, type) VALUES (899, "Combat Torque", "fighting");
INSERT INTO attack(id, name, type) VALUES (900, "Magical Torque", "fairy");
INSERT INTO attack(id, name, type) VALUES (901, "Blood Moon", "normal");
INSERT INTO attack(id, name, type) VALUES (902, "Matcha Gotcha", "grass");
INSERT INTO attack(id, name, type) VALUES (903, "Syrup Bomb", "grass");
INSERT INTO attack(id, name, type) VALUES (904, "Ivy Cudgel", "grass");
INSERT INTO attack(id, name, type) VALUES (905, "Electro Shot", "electric");
INSERT INTO attack(id, name, type) VALUES (906, "Tera Starstorm", "normal");
INSERT INTO attack(id, name, type) VALUES (907, "Fickle Beam", "dragon");
INSERT INTO attack(id, name, type) VALUES (908, "Burning Bulwark", "fire");
INSERT INTO attack(id, name, type) VALUES (909, "Thunderclap", "electric");
INSERT INTO attack(id, name, type) VALUES (910, "Mighty Cleave", "rock");
INSERT INTO attack(id, name, type) VALUES (911, "Tachyon Cutter", "steel");
INSERT INTO attack(id, name, type) VALUES (912, "Hard Press", "steel");
INSERT INTO attack(id, name, type) VALUES (913, "Dragon Cheer", "dragon");
INSERT INTO attack(id, name, type) VALUES (914, "Alluring Voice", "fairy");
INSERT INTO attack(id, name, type) VALUES (915, "Temper Flare", "fire");
INSERT INTO attack(id, name, type) VALUES (916, "Supercell Slam", "electric");
INSERT INTO attack(id, name, type) VALUES (917, "Psychic Noise", "psychic");
INSERT INTO attack(id, name, type) VALUES (918, "Upper Hand", "fighting");
INSERT INTO attack(id, name, type) VALUES (919, "Malignant Chain", "poison");
